const localeToCountry = {
    'af-ZA': 'South Africa',
    'sq-AL': 'Albania',
    'ar-DZ': 'Algeria',
    'ar-BH': 'Bahrain',
    'ar-EG': 'Egypt',
    'ar-IQ': 'Iraq',
    'ar-JO': 'Jordan',
    'ar-KW': 'Kuwait',
    'ar-LB': 'Lebanon',
    'ar-LY': 'Libya',
    'ar-MA': 'Morocco',
    'ar-OM': 'Oman',
    'ar-QA': 'Qatar',
    'ar-SA': 'Saudi Arabia',
    'ar-SD': 'Sudan',
    'ar-SY': 'Syria',
    'ar-TN': 'Tunisia',
    'ar-YE': 'Yemen',
    'hy-AM': 'Armenia',
    'as-IN': 'India',
    'az-AZ': 'Azerbaijan',
    'ba-RU': 'Bashkortostan',
    'eu-ES': 'Basque Country',
    'bn-BD': 'Bangladesh',
    'bn-IN': 'India',
    'bs-BA': 'Bosnia and Herzegovina',
    'ca-ES': 'Catalonia',
    'hr-HR': 'Croatia',
    'cs-CZ': 'Czech Republic',
    'da-DK': 'Denmark',
    'nl-BE': 'Belgium',
    'nl-NL': 'Netherlands',
    'en-AU': 'Australia',
    'en-BZ': 'Belize',
    'en-CA': 'Canada',
    'en-GH': 'Ghana',
    'en-GI': 'Gibraltar',
    'en-IE': 'Ireland',
    'en-IN': 'India',
    'en-JM': 'Jamaica',
    'en-MT': 'Malta',
    'en-NZ': 'New Zealand',
    'en-PH': 'Philippines',
    'en-SG': 'Singapore',
    'en-TT': 'Trinidad and Tobago',
    'en-GB': 'United Kingdom',
    'en-US': 'United States',
    'en-ZA': 'South Africa',
    'eo': 'Esperanto',
    'et-EE': 'Estonia',
    'fo-FO': 'Faroe Islands',
    'fi-FI': 'Finland',
    'fr-BE': 'Belgium',
    'fr-CA': 'Canada',
    'fr-FR': 'France',
    'fr-LU': 'Luxembourg',
    'fr-MC': 'Monaco',
    'gl-ES': 'Galicia',
    'ka-GE': 'Georgia',
    'de-AT': 'Austria',
    'de-CH': 'Switzerland',
    'de-DE': 'Germany',
    'de-LI': 'Liechtenstein',
    'de-LU': 'Luxembourg',
    'el-CY': 'Cyprus',
    'el-GR': 'Greece',
    'gu-IN': 'India',
    'he-IL': 'Israel',
    'hi-IN': 'India',
    'hu-HU': 'Hungary',
    'id-ID': 'Indonesia',
    'ig-NG': 'Nigeria',
    'is-IS': 'Iceland',
    'it-CH': 'Switzerland',
    'it-IT': 'Italy',
    'ja-JP': 'Japan',
    'jw-ID': 'Indonesia',
    'kk-KZ': 'Kazakhstan',
    'km-KH': 'Cambodia',
    'kn-IN': 'India',
    'ko-KR': 'South Korea',
    'ku-TR': 'Turkey',
    'ky-KG': 'Kyrgyzstan',
    'la': 'Latin',
    'lb-LU': 'Luxembourg',
    'lo-LA': 'Laos',
    'lt-LT': 'Lithuania',
    'lv-LV': 'Latvia',
    'mg-MG': 'Madagascar',
    'mi-NZ': 'New Zealand',
    'mk-MK': 'North Macedonia',
    'ml-IN': 'India',
    'mn-MN': 'Mongolia',
    'mr-IN': 'India',
    'ms-MY': 'Malaysia',
    'mt-MT': 'Malta',
    'my-MM': 'Myanmar',
    'nb-NO': 'Norway',
    'ne-IN': 'India',
    'ne-NP': 'Nepal',
    'no-NO': 'Norway',
    'or-IN': 'India',
    'pa-IN': 'India',
    'pl-PL': 'Poland',
    'ps-AF': 'Afghanistan',
    'pt-BR': 'Brazil',
    'pt-PT': 'Portugal',
    'qu-PE': 'Peru',
    'rm-CH': 'Switzerland',
    'rn-BI': 'Burundi',
    'ro-RO': 'Romania',
    'ru-RU': 'Russia',
    'rw-RW': 'Rwanda',
    'si-LK': 'Sri Lanka',
    'sk-SK': 'Slovakia',
    'sl-SI': 'Slovenia',
    'sm-WS': 'Samoa',
    'sn-ZW': 'Zimbabwe',
    'so-DJ': 'Djibouti',
    'so-ET': 'Ethiopia',
    'so-KE': 'Kenya',
    'so-SO': 'Somalia',
    'sr-Cyrl-RS': 'Serbia',
    'sr-Latn-RS': 'Serbia',
    'ss-ZA': 'Swaziland',
    'st-ZA': 'South Africa',
    'su-ID': 'Indonesia',
    'sv-SE': 'Sweden',
    'sw-TZ': 'Tanzania',
    'sw-KE': 'Kenya',
    'ta-IN': 'India',
    'ta-LK': 'Sri Lanka',
    'te-IN': 'India',
    'tg-TJ': 'Tajikistan',
    'th-TH': 'Thailand',
    'tr-TR': 'Turkey',
    'ts-ZA': 'South Africa',
    'tt-RU': 'Russia',
    'uk-UA': 'Ukraine',
    'ur-PK': 'Pakistan',
    'uz-UZ': 'Uzbekistan',
    'vi-VN': 'Vietnam',
    'vo': 'Volapük',
    'wa-BE': 'Belgium',
    'wo-SN': 'Senegal',
    'xh-ZA': 'South Africa',
    'yi': 'Yiddish',
    'yo-NG': 'Nigeria',
    'zu-ZA': 'South Africa',
    'ar-PS': 'Palestine',
    'en-AG': 'Antigua and Barbuda',
    'en-BW': 'Botswana',
    'en-FJ': 'Fiji',
    'en-GY': 'Guyana',
    'en-MW': 'Malawi',
    'en-MY': 'Malaysia',
    'en-NA': 'Namibia',
    'en-RW': 'Rwanda',
    'en-SL': 'Sierra Leone',
    'en-TZ': 'Tanzania',
    'en-UG': 'Uganda',
    'en-VI': 'U.S. Virgin Islands',
    'es-CL': 'Chile',
    'es-CO': 'Colombia',
    'es-CR': 'Costa Rica',
    'es-DZ': 'Algeria',
    'es-EC': 'Ecuador',
    'es-GQ': 'Equatorial Guinea',
    'es-GT': 'Guatemala',
    'es-HN': 'Honduras',
    'es-MX': 'Mexico',
    'es-NI': 'Nicaragua',
    'es-PA': 'Panama',
    'es-PE': 'Peru',
    'es-PR': 'Puerto Rico',
    'es-SV': 'El Salvador',
    'es-US': 'United States',
    'es-VE': 'Venezuela',
    'fr-CM': 'Cameroon',
    'fr-GA': 'Gabon',
    'fr-MR': 'Mauritania',
    'fr-NE': 'Niger',
    'fr-RW': 'Rwanda',
    'fr-SN': 'Senegal',
    'fr-TG': 'Togo',
    'it-SM': 'San Marino',
    'pt-AO': 'Angola',
    'pt-CV': 'Cape Verde',
    'pt-GW': 'Guinea-Bissau',
    'pt-MZ': 'Mozambique',
    'pt-ST': 'São Tomé and Príncipe',
    'pt-TL': 'Timor-Leste',
    'ru-KG': 'Kyrgyzstan',
    'ru-MD': 'Moldova',
    'uk-KY': 'Cayman Islands',
    'uk-GB': 'United Kingdom',
    'zh-CN': 'China',
    'zh-HK': 'Hong Kong',
    'zh-MO': 'Macau',
    'zh-SG': 'Singapore',
    'zh-TW': 'Taiwan',
}as const; // Use `as const` to ensure type inference for the object keys

type Locale = keyof typeof localeToCountry; // Create a type from the keys of localeToCountry

// export default localeToCountry;

/**
 * Get the country name based on the locale code.
 * @param {Locale} locale - The locale code (e.g., 'en-US', 'fr-FR').
 * @returns {string} - The country name corresponding to the locale.
 */
export function getCountryFromLocale(locale: Locale): string {
    // Look up the country based on the locale code
    const country = localeToCountry[locale];
    
    // If the locale is not found, return a default message
    if (country) {
        return country;
    } else {
        return 'Country not found for this locale';
    }
}